version: '3'
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
